version: 1.0
frontend:  
  phases:  
    preBuild:  
      commands:  
        - curl -sSL https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.sh > dotnet-install.sh  
        - chmod +x *.sh  
        - ./dotnet-install.sh -c 6.0 -InstallDir ./dotnet6  
        - ./dotnet6/dotnet --version  
    build:  
      commands:  
        - ./dotnet6/dotnet publish -c release -o release  
  artifacts:   
   baseDirectory: /bin/Release/net6.0/publish
    files:  
      - '**/*'  
  cache:  
    paths: []